services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - HOSTNAME=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

